// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVljNwwDZkV9K2zl6a65Eo9Hv8d2cbCjI',
    appId: '1:101219994960:web:46ff3ccd09c88be87b7055',
    messagingSenderId: '101219994960',
    projectId: 'loginscreen-a9d17',
    authDomain: 'loginscreen-a9d17.firebaseapp.com',
    storageBucket: 'loginscreen-a9d17.appspot.com',
    measurementId: 'G-VVJQLM52V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2gsxOl30u7nvDf0mt7_G-dCnGfSUPra4',
    appId: '1:101219994960:android:08738b2e3e8abce47b7055',
    messagingSenderId: '101219994960',
    projectId: 'loginscreen-a9d17',
    storageBucket: 'loginscreen-a9d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqm8VgbmdvnUcS3izolQDutQx8WksA_6A',
    appId: '1:101219994960:ios:9e79c04b348f4ca47b7055',
    messagingSenderId: '101219994960',
    projectId: 'loginscreen-a9d17',
    storageBucket: 'loginscreen-a9d17.appspot.com',
    iosBundleId: 'com.example.createuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqm8VgbmdvnUcS3izolQDutQx8WksA_6A',
    appId: '1:101219994960:ios:88201f58d2e526237b7055',
    messagingSenderId: '101219994960',
    projectId: 'loginscreen-a9d17',
    storageBucket: 'loginscreen-a9d17.appspot.com',
    iosBundleId: 'com.example.createuser.RunnerTests',
  );
}
